# Data Preprocessing Tools

In [41]:
from Packages import *

In [74]:
# Load Data
df = pd.read_csv('Loan_application.csv')
df.head()

Age  Salary  Education  Capital  Loan
0   19   19000          0        2     0
1   35   20000          0        2     0
2   26   43000          0        0     0
3   27   57000          0        0     0
4   19   76000          1        0     0

In [75]:
# check the missing
df.isnull().sum()

Age          0
Salary       0
Education    0
Capital      0
Loan         0
dtype: int64

In [76]:
# Define Dep and Indep variables
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
x

array([[   19, 19000,     0,     2],
       [   35, 20000,     0,     2],
       [   26, 43000,     0,     0],
       ...,
       [   50, 20000,     0,     3],
       [   36, 33000,     0,     0],
       [   49, 36000,     1,     1]], dtype=int64)

In [77]:
# Train/ Test Split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=9)

In [46]:
# Feature Scalling
ss = StandardScaler()
x_train[:,[0,1]] = ss.fit_transform(x_train[:,[0,1]] )
x_test[:,[0,1]] = ss.transform(x_test[:,[0,1]])
x_train

array([[ 0,  0,  1,  2],
       [-1,  0,  1,  0],
       [ 0,  0,  0,  2],
       ...,
       [ 0,  0,  0,  2],
       [ 0,  0,  1,  1],
       [ 0,  2,  1,  2]], dtype=int64)

# Making Model

In [47]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
results = LogisticRegression(random_state=0)
results.fit(x_train,y_train)

LogisticRegression(random_state=0)

# Evaluation Metric (F1-Score)

In [48]:
from sklearn.metrics import *

In [49]:
y_pred = results.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [50]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[34,  9],
       [ 6, 31]], dtype=int64)

In [51]:
accuracy_score(y_test,y_pred)

0.8125

In [52]:
recall_score(y_test,y_pred)

0.8378378378378378

In [53]:
f1_score(y_test,y_pred)

0.8051948051948052

In [54]:
# Probability Prediction
probability = results.predict_proba(x_test)
probability

array([[0.56216206, 0.43783794],
       [0.96459969, 0.03540031],
       [0.94906707, 0.05093293],
       [0.83802731, 0.16197269],
       [0.93671671, 0.06328329],
       [0.98076574, 0.01923426],
       [0.31935675, 0.68064325],
       [0.25118797, 0.74881203],
       [0.03491083, 0.96508917],
       [0.3962362 , 0.6037638 ],
       [0.19600888, 0.80399112],
       [0.48971399, 0.51028601],
       [0.56216206, 0.43783794],
       [0.91009021, 0.08990979],
       [0.92417556, 0.07582444],
       [0.46752543, 0.53247457],
       [0.25118797, 0.74881203],
       [0.31935675, 0.68064325],
       [0.95975125, 0.04024875],
       [0.56216206, 0.43783794],
       [0.32909883, 0.67090117],
       [0.96459969, 0.03540031],
       [0.56216206, 0.43783794],
       [0.47860916, 0.52139084],
       [0.87859371, 0.12140629],
       [0.56216206, 0.43783794],
       [0.78718935, 0.21281065],
       [0.3962362 , 0.6037638 ],
       [0.90638479, 0.09361521],
       [0.57307472, 0.42692528],
       [0.

In [55]:
# save model Architecture
import pickle
pickle.dump(results, open('mymodel.pkl', 'wb'))

In [68]:
## Test data
x_test_data = pd.read_csv('Loan_application.csv')
x_test_data.head()

Age  Salary  Education  Capital  Loan
0   19   19000          0        2     0
1   35   20000          0        2     0
2   26   43000          0        0     0
3   27   57000          0        0     0
4   19   76000          1        0     0

In [69]:
x_test_copydata = x_test_data.copy()

In [80]:
# Feature Scaling 
import warnings
import statsmodels.api as sm
warnings.filterwarnings('ignore')
x_test_data[['Age','Salary']] = ss.transform(x_test_data[['Age','Salary']])

In [1]:
x_test_data = sm.add_constant(x_test_data, has_constant='add')
x_test_data = x_test_data[x_train.columns]

# Make predictions
Prediction = results.predict(x_test_data)
print(Prediction)


NameError: name 'sm' is not defined

In [78]:
# x_test_data
x_test_data = x_test_data.reindex(columns=x_train.columns, fill_value=0)

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [73]:
# Prediction 
Prediction = results.predict(x_test_data)
Prediction

ValueError: X has 5 features, but LogisticRegression is expecting 4 features as input.

In [61]:
# Probability Prediction
Probability = results.predict_proba(x_test_data)
Probability

NameError: name 'x_test_data' is not defined

In [62]:
# select the probability of 1
Probability = Probability[:,1]
Probability

NameError: name 'Probability' is not defined

In [63]:
Prediction = pd.DataFrame(Prediction)
Probability = pd.DataFrame(Probability)

NameError: name 'Prediction' is not defined

In [64]:
x_test_copydata = x_test_copydata.join(Probability)

NameError: name 'x_test_copydata' is not defined

In [65]:
x_test_copydata.rename(columns={0:"Probability"},inplace=True)
x_test_copydata

NameError: name 'x_test_copydata' is not defined

In [66]:
x_test_copydata = x_test_copydata.join(Prediction)
x_test_copydata.rename(columns={0:"Prediction"})

NameError: name 'x_test_copydata' is not defined

In [67]:
# Save the data
x_test_copydata.to_csv("Ready_Data.csv",index=False)

NameError: name 'x_test_copydata' is not defined