In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
print(pd.__version__)

2.2.2


In [16]:
dataset= pd.read_csv('Loan_application.csv')
# or 
path= r'C:\Users\user\Documents\B-TECH\ML\Loan with Gradio\Loan_application.csv'
data= pd.read_csv(path)
data.head()

Age  Salary  Education  Capital  Loan
0   19   19000          0        2     0
1   35   20000          0        2     0
2   26   43000          0        0     0
3   27   57000          0        0     0
4   19   76000          1        0     0

In [14]:
data.describe()

Age        Salary   Education     Capital      Loan
count  400.000000     400.00000  400.000000  400.000000  400.0000
mean    39.490000   69650.00000    0.595000    1.920000    0.4375
std     11.479955   34119.24394    0.491507    1.355801    0.4967
min     18.000000   15000.00000    0.000000    0.000000    0.0000
25%     31.000000   43000.00000    0.000000    1.000000    0.0000
50%     38.000000   69500.00000    1.000000    2.000000    0.0000
75%     47.000000   88000.00000    1.000000    3.000000    1.0000
max     76.000000  150000.00000    1.000000    4.000000    1.0000

In [4]:
dataset.head()

Age  Salary  Education  Capital  Loan
0   19   19000          0        2     0
1   35   20000          0        2     0
2   26   43000          0        0     0
3   27   57000          0        0     0
4   19   76000          1        0     0

In [8]:
dataset.tail

<bound method NDFrame.tail of      Age  Salary  Education  Capital  Loan
0     19   19000          0        2     0
1     35   20000          0        2     0
2     26   43000          0        0     0
3     27   57000          0        0     0
4     19   76000          1        0     0
..   ...     ...        ...      ...   ...
395   46   41000          1        3     0
396   51   23000          0        4     0
397   50   20000          0        3     0
398   36   33000          0        0     0
399   49   36000          1        1     0

[400 rows x 5 columns]>

In [9]:
dataset.shape

(400, 5)

In [10]:
dataset.isnull()

Age  Salary  Education  Capital   Loan
0    False   False      False    False  False
1    False   False      False    False  False
2    False   False      False    False  False
3    False   False      False    False  False
4    False   False      False    False  False
..     ...     ...        ...      ...    ...
395  False   False      False    False  False
396  False   False      False    False  False
397  False   False      False    False  False
398  False   False      False    False  False
399  False   False      False    False  False

[400 rows x 5 columns]

In [18]:
dataset.isnull().sum()

Age          0
Salary       0
Education    0
Capital      0
Loan         0
dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        400 non-null    int64
 1   Salary     400 non-null    int64
 2   Education  400 non-null    int64
 3   Capital    400 non-null    int64
 4   Loan       400 non-null    int64
dtypes: int64(5)
memory usage: 15.8 KB


In [22]:
# x is dependent y is independent

x= data[['Age', 'Salary', 'Education', 'Capital']]
y= data[[ 'Loan']]

In [20]:
print(x)

     Age  Salary  Education  Capital
0     19   19000          0        2
1     35   20000          0        2
2     26   43000          0        0
3     27   57000          0        0
4     19   76000          1        0
..   ...     ...        ...      ...
395   46   41000          1        3
396   51   23000          0        4
397   50   20000          0        3
398   36   33000          0        0
399   49   36000          1        1

[400 rows x 4 columns]


In [21]:
print(y)

     Loan
0       0
1       0
2       0
3       0
4       0
..    ...
395     0
396     0
397     0
398     0
399     0

[400 rows x 1 columns]


In [26]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=9)

In [49]:
# ss = Stafrom sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)
print(x_train)
print(x_test)

[[-0.99184151  0.41122781  0.8325393   0.06547205]
 [-1.59887019  0.05866813  0.8325393  -1.43103191]
 [-0.03793929  0.02928816 -1.20114449  0.06547205]
 ...
 [ 0.22221586 -0.14699168 -1.20114449  0.06547205]
 [-0.03793929  0.205568    0.8325393  -0.68277993]
 [ 0.39565262  2.02712635  0.8325393   0.06547205]]
[[-9.91841510e-01  2.64327947e-01  8.32539304e-01 -1.43103191e+00]
 [-1.59887019e+00 -1.58661037e+00 -1.20114449e+00  6.54720482e-02]
 [ 4.82371008e-01 -1.29281064e+00 -1.20114449e+00  8.13724028e-01]
 [-3.84812826e-01  2.92881609e-02 -1.20114449e+00  8.13724028e-01]
 [-1.16527828e+00 -7.93351092e-01 -1.20114449e+00 -1.43103191e+00]
 [ 5.69089391e-01 -1.23405069e+00 -1.20114449e+00 -1.43103191e+00]
 [ 4.87790907e-02  1.46808054e-01  8.32539304e-01  8.13724028e-01]
 [-3.84812826e-01  8.80481075e-02  8.32539304e-01  1.56197601e+00]
 [ 6.55807775e-01  2.17402621e+00  8.32539304e-01  8.13724028e-01]
 [ 5.69089391e-01  1.17428081e-01  8.32539304e-01  6.54720482e-02]
 [ 1.34955484e+00 

In [51]:
ss = StandardScaler()
x_train[[0, 1]] = ss.fit_transform(x_train[[0, 1]])
x_test[[0, 1]] = ss.transform(x_test[[0, 1]])

# x_test.shape()
# x_train.shape()

In [52]:
print(x_train)

[[ 1.          1.          0.          1.        ]
 [-1.         -1.          0.         -1.        ]
 [-0.03793929  0.02928816 -1.20114449  0.06547205]
 ...
 [ 0.22221586 -0.14699168 -1.20114449  0.06547205]
 [-0.03793929  0.205568    0.8325393  -0.68277993]
 [ 0.39565262  2.02712635  0.8325393   0.06547205]]
